name: movieapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.5
  flutter_staggered_grid_view: ^0.6.2
  google_fonts: ^3.0.1
  tmdb_api: ^2.1.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  assets:
     - assets/
     - assets/images/

 # fonts:
  #  - family: Poppins
   #   fonts:
 #        - asset: assets/fonts/PoppinsSemiBold.ttf
  #       - asset: assets/fonts/PoppinsRegular.ttf
   #      - asset: assets/fonts/PoppinsMedium.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700